site_name: Verificação e validação dos aplicativos de governo
pages:
  - Inicio: index.md
  - Gov.Br: govbr.md
  - Versões: 
    - Versão 1.0.0: 
      - Capacidade de ir e vir: feature1.md
      - Experiência do Usuário: feature2.md
      - Instalação do aplicativo: feature3.md
    - Versão 1.1.0: 
      - Capacidade de ir e vir: feature4.md
      - Experiência do Usuário: feature6.md
      - Forçar falhas nos campos de input: feature5.md
    - Versão 1.2.0:
      - Atualizar o aplicativo: feature8.md 
      - Capacidade de ir e vir: feature7.md
      - Experiência do Usuário: feature9.md
      - Recuperação de senha: feature10.md
      - Validação facial: feature11.md
    - Versão 1.4.0:
      - Capacidade de ir e vir: feature12.md
      - Experiência do Usuário: feature13.md
      




